import gtg_logo from "../../../../images/logo/gtg-logo.svg";
import npkt from "../../../../images/logo/CompositeLayer.svg";
import dtk from "../../../../images/logo/dtk.svg";

export default {
  // title: "time",
  //   layout: "first",
  time_sec: [
    {
      id: 1,
      title: "Collector Bank Arena (GTG)",
      image: gtg_logo,
      location: "Danderyd",
      km: "3 km bort",
      favourite: "active",
      bg: "#0a3133",
      times: [
        "6:00",
        "7:00",
        "8:00",
        "9:00",
        "10:00",
        "11:00",
        "12:00",
        "13:00",
        "14:00",
        "15:00",
        "16:00",
        "17:00",
        "18:00",
        "19:00",
        "20:00",
      ],

      table_data: {
        title: "Tillgängliga banor",
        date: "Fredag 22 juni, 16:00",
        table_row: [
          {
            col_1: "Bana 1",
            time: "60 min",
            sport: { sport: "Tennis", location: "Hard court • Inomhus" },
            kr: "150 kr",
          },
          {
            col_1: "Bana 1",
            time: "60 min",
            sport: { sport: "Tennis", location: "Hard court • Inomhus" },
            kr: "150 kr",
          },
        ],
      },
    },
    {
      id: 2,
      title: "Näsbyparks TK",
      image: npkt,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#5369a3",
      times: ["14:00", "15:00", "16:00", "17:00", "18:00", "19:00"],
    },
    {
      id: 3,
      title: "Näsbyparks TK",
      image: npkt,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#5369a3",
      times: ["14:00", "15:00", "16:00", "17:00", "18:00", "19:00"],
    },
    {
      id: 4,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 5,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 6,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 7,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 8,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 9,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
    {
      id: 10,
      title: "Danderyds TK",
      image: dtk,
      location: "Täby",
      km: "",
      favourite: "Favourite",
      bg: "#53a378",
    },
  ],
};
